/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilCipherBase implements java.lang.AutoCloseable {
	private long swigCPtr;
	protected boolean swigCMemOwn;

	protected VirgilCipherBase(long cPtr, boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	protected static long getCPtr(VirgilCipherBase obj) {
		return (obj == null) ? 0 : obj.swigCPtr;
	}

	protected void finalize() {
		delete();
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				virgil_crypto_javaJNI.delete_VirgilCipherBase(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	@Override
	public void close() {
		delete();
	}

	public VirgilCipherBase() {
		this(virgil_crypto_javaJNI.new_VirgilCipherBase(), true);
	}

	public void addKeyRecipient(byte[] recipientId, byte[] publicKey) {
		virgil_crypto_javaJNI.VirgilCipherBase_addKeyRecipient(swigCPtr, this, recipientId, publicKey);
	}

	public void removeKeyRecipient(byte[] recipientId) {
		virgil_crypto_javaJNI.VirgilCipherBase_removeKeyRecipient(swigCPtr, this, recipientId);
	}

	public boolean keyRecipientExists(byte[] recipientId) {
		return virgil_crypto_javaJNI.VirgilCipherBase_keyRecipientExists(swigCPtr, this, recipientId);
	}

	public void addPasswordRecipient(byte[] pwd) {
		virgil_crypto_javaJNI.VirgilCipherBase_addPasswordRecipient(swigCPtr, this, pwd);
	}

	public void removePasswordRecipient(byte[] pwd) {
		virgil_crypto_javaJNI.VirgilCipherBase_removePasswordRecipient(swigCPtr, this, pwd);
	}

	public void removeAllRecipients() {
		virgil_crypto_javaJNI.VirgilCipherBase_removeAllRecipients(swigCPtr, this);
	}

	public byte[] getContentInfo() {
		return virgil_crypto_javaJNI.VirgilCipherBase_getContentInfo(swigCPtr, this);
	}

	public void setContentInfo(byte[] contentInfo) {
		virgil_crypto_javaJNI.VirgilCipherBase_setContentInfo(swigCPtr, this, contentInfo);
	}

	public static long defineContentInfoSize(byte[] data) {
		return virgil_crypto_javaJNI.VirgilCipherBase_defineContentInfoSize(data);
	}

	public VirgilCustomParams customParams() {
		return new VirgilCustomParams(virgil_crypto_javaJNI.VirgilCipherBase_customParams__SWIG_0(swigCPtr, this),
				false);
	}

}
