/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.virgilsecurity.crypto;

public class VirgilAsn1Compatible implements java.lang.AutoCloseable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VirgilAsn1Compatible(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VirgilAsn1Compatible obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        virgil_crypto_javaJNI.delete_VirgilAsn1Compatible(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
    delete();
  }

  public byte[] toAsn1() {
    return virgil_crypto_javaJNI.VirgilAsn1Compatible_toAsn1(swigCPtr, this);
  }

  public void fromAsn1(byte[] asn1) {
    virgil_crypto_javaJNI.VirgilAsn1Compatible_fromAsn1(swigCPtr, this, asn1);
  }

}
