/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_virgil_crypto_java_WRAP_H_
#define SWIG_virgil_crypto_java_WRAP_H_

class SwigDirector_VirgilDataSource : public virgil::crypto::VirgilDataSource, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_VirgilDataSource(JNIEnv *jenv);
    virtual bool hasData();
    virtual virgil::crypto::VirgilByteArray read();
    virtual ~SwigDirector_VirgilDataSource() throw ();
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    bool swig_override[2];
};

class SwigDirector_VirgilDataSink : public virgil::crypto::VirgilDataSink, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_VirgilDataSink(JNIEnv *jenv);
    virtual bool isGood();
    virtual void write(virgil::crypto::VirgilByteArray const &data);
    virtual ~SwigDirector_VirgilDataSink() throw ();
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    bool swig_override[2];
};


#endif
